import hmac
import hashlib
import os
import logging
from typing import Optional
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
import requests

router = APIRouter()
logger = logging.getLogger(__name__)

class CreateOrderRequest(BaseModel):
    amount: int = Field(..., description="Amount in paise (minimum 100)")
    currency: str = Field("INR", description="Currency ISO code")
    receipt: Optional[str] = Field(None, description="Receipt identifier")

class VerifyPaymentRequest(BaseModel):
    razorpay_order_id: Optional[str] = None
    order_id: Optional[str] = None
    razorpay_payment_id: Optional[str] = None
    payment_id: Optional[str] = None
    razorpay_signature: Optional[str] = None
    signature: Optional[str] = None

@router.post("/create-order")
def create_order(request: CreateOrderRequest):
    """
    Creates an order on Razorpay for standard checkout.
    Minimum amount: 100 paise (₹1.00)
    """
    key_id = os.getenv("RAZORPAY_KEY_ID")
    key_secret = os.getenv("RAZORPAY_KEY_SECRET")

    if not key_id or not key_secret:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Razorpay credentials not configured or unauthorized"
        )

    if request.amount < 100:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Amount must be at least 100 paise (₹1.00)"
        )

    receipt = request.receipt or f"rcpt_{int(os.times().system * 1000)}"

    try:
        response = requests.post(
            "https://api.razorpay.com/v1/orders",
            auth=(key_id, key_secret),
            json={
                "amount": request.amount,
                "currency": request.currency.upper(),
                "receipt": receipt
            },
            timeout=10
        )

        if response.status_code == 401:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Razorpay API authentication failed"
            )

        if not response.ok:
            logger.error(f"Razorpay API error: {response.status_code} - {response.text}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Razorpay error: {response.text}"
            )

        data = response.json()
        return {
            "order_id": data.get("id"),
            "amount": data.get("amount"),
            "currency": data.get("currency")
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to create Razorpay order: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.post("/verify-payment")
def verify_payment(request: VerifyPaymentRequest):
    """
    Verifies the HMAC-SHA256 signature generated by Razorpay Checkout.
    Algorithm: HMAC-SHA256(order_id + "|" + payment_id, KEY_SECRET)
    """
    key_secret = os.getenv("RAZORPAY_KEY_SECRET")
    if not key_secret:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Razorpay secret key not configured"
        )

    order_id = request.razorpay_order_id or request.order_id
    payment_id = request.razorpay_payment_id or request.payment_id
    signature = request.razorpay_signature or request.signature

    if not order_id or not payment_id or not signature:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Missing required fields: order_id, payment_id, and signature are required"
        )

    payload = f"{order_id}|{payment_id}".encode("utf-8")
    generated_sig = hmac.new(
        key_secret.encode("utf-8"),
        payload,
        hashlib.sha256
    ).hexdigest()

    if not hmac.compare_digest(generated_sig, signature):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid signature: payment verification failed"
        )

    return {
        "success": True,
        "message": "Payment verified successfully",
        "payment_id": payment_id,
        "order_id": order_id
    }
