# backend/app/services/chain_client.py
import json
import os

try:
    from web3 import Web3
    # Connect to local Anvil node
    RPC_URL = os.getenv("RPC_URL", "http://127.0.0.1:8545")
    w3 = Web3(Web3.HTTPProvider(RPC_URL))
    if not w3.is_connected():
        print("INFO: Local Anvil blockchain node not connected. Using mock/simulation mode.")
except Exception as e:
    Web3 = None
    w3 = None
    print(f"INFO: web3 not initialized: {e}")

# Deployed Anvil Addresses
ESCROW_ADDRESS = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
GRADE_REGISTRY_ADDRESS = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
DISPUTE_ARBITER_ADDRESS = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"

def get_contract_abi(contract_name: str):
    """
    Dynamically loads the ABI generated by Foundry.
    Navigates from backend/app/services -> backend -> TeamNeuroBytes -> blockchain/out/
    """
    current_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(os.path.dirname(os.path.dirname(current_dir)))
    
    abi_path = os.path.join(
        root_dir, 
        "blockchain", 
        "out", 
        f"{contract_name}.sol", 
        f"{contract_name}.json"
    )
    
    try:
        with open(abi_path, 'r') as f:
            data = json.load(f)
            return data['abi']
    except FileNotFoundError:
        return []

def get_escrow_contract():
    if not w3:
        return None
    abi = get_contract_abi("EscrowManager")
    return w3.eth.contract(address=ESCROW_ADDRESS, abi=abi)

def get_grade_registry_contract():
    if not w3:
        return None
    abi = get_contract_abi("GradeRegistry")
    return w3.eth.contract(address=GRADE_REGISTRY_ADDRESS, abi=abi)